export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const FILTER_PRODUCTS_REQUEST = "FILTER_PRODUCTS_REQUEST";
export const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS";
export const FILTER_PRODUCTS_FAILURE = "FILTER_PRODUCTS_FAILURE";

export const FILTER_BRANDS_REQUEST = "FILTER_BRANDS_REQUEST";
export const FILTER_BRANDS_SUCCESS = "FILTER_BRANDS_SUCCESS";
export const FILTER_BRANDS_FAILURE = "FILTER_BRANDS_FAILURE";
